# coding: utf-8

"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.sort import Sort


class TestSort(unittest.TestCase):
    """Sort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_Sort(self):
        """Test Sort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Sort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
