# coding: utf-8

"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import flathub
from flathub.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attachment(self):
        """Test case for attachment

        Download a row attachment  # noqa: E501
        """
        pass

    def test_attachments(self):
        """Test case for attachments

        Download attachments in bulk from matching rows for multiple fields  # noqa: E501
        """
        pass

    def test_attachments1(self):
        """Test case for attachments1

        Download attachments in bulk from matching rows for single field  # noqa: E501
        """
        pass

    def test_attachments1_post(self):
        """Test case for attachments1_post

        Download attachments in bulk from matching rows for single field  # noqa: E501
        """
        pass

    def test_attachments_post(self):
        """Test case for attachments_post

        Download attachments in bulk from matching rows for multiple fields  # noqa: E501
        """
        pass

    def test_catalog(self):
        """Test case for catalog

        Get full metadata about a specific catalog  # noqa: E501
        """
        pass

    def test_count(self):
        """Test case for count

        Get count of matching rows (given some filters)  # noqa: E501
        """
        pass

    def test_count_post(self):
        """Test case for count_post

        Get count of matching rows (given some filters)  # noqa: E501
        """
        pass

    def test_data(self):
        """Test case for data

        Get a sample of raw data rows  # noqa: E501
        """
        pass

    def test_data_post(self):
        """Test case for data_post

        Get a sample of raw data rows  # noqa: E501
        """
        pass

    def test_download(self):
        """Test case for download

        Download raw data in bulk  # noqa: E501
        """
        pass

    def test_download_post(self):
        """Test case for download_post

        Download raw data in bulk  # noqa: E501
        """
        pass

    def test_histogram(self):
        """Test case for histogram

        Get a histogram of data across one or more fields  # noqa: E501
        """
        pass

    def test_histogram_post(self):
        """Test case for histogram_post

        Get a histogram of data across one or more fields  # noqa: E501
        """
        pass

    def test_schema_csv(self):
        """Test case for schema_csv

        Get a CSV representation of the catalog schema (no data)  # noqa: E501
        """
        pass

    def test_schema_sql(self):
        """Test case for schema_sql

        Get a SQL representation of the catalog schema (no data)  # noqa: E501
        """
        pass

    def test_stats(self):
        """Test case for stats

        Get statistics about fields (given some filters)  # noqa: E501
        """
        pass

    def test_stats_post(self):
        """Test case for stats_post

        Get statistics about fields (given some filters)  # noqa: E501
        """
        pass

    def test_top(self):
        """Test case for top

        Get the list of available dataset catalogs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
