# coding: utf-8

"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import flathub
from flathub.model.catalog_meta import CatalogMeta


class TestCatalogMeta(unittest.TestCase):
    """CatalogMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_CatalogMeta(self):
        """Test CatalogMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CatalogMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
