# coding: utf-8

"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.api_client import ApiClient
from openapi_client.api.default_api_endpoints.attachment import Attachment
from openapi_client.api.default_api_endpoints.attachments import Attachments
from openapi_client.api.default_api_endpoints.attachments1 import Attachments1
from openapi_client.api.default_api_endpoints.attachments1_post import Attachments1Post
from openapi_client.api.default_api_endpoints.attachments_post import AttachmentsPost
from openapi_client.api.default_api_endpoints.catalog import Catalog
from openapi_client.api.default_api_endpoints.count import Count
from openapi_client.api.default_api_endpoints.count_post import CountPost
from openapi_client.api.default_api_endpoints.data import Data
from openapi_client.api.default_api_endpoints.data_post import DataPost
from openapi_client.api.default_api_endpoints.download import Download
from openapi_client.api.default_api_endpoints.download_post import DownloadPost
from openapi_client.api.default_api_endpoints.histogram import Histogram
from openapi_client.api.default_api_endpoints.histogram_post import HistogramPost
from openapi_client.api.default_api_endpoints.schema_csv import SchemaCsv
from openapi_client.api.default_api_endpoints.schema_sql import SchemaSql
from openapi_client.api.default_api_endpoints.stats import Stats
from openapi_client.api.default_api_endpoints.stats_post import StatsPost
from openapi_client.api.default_api_endpoints.top import Top


class DefaultApi(
    Attachment,
    Attachments,
    Attachments1,
    Attachments1Post,
    AttachmentsPost,
    Catalog,
    Count,
    CountPost,
    Data,
    DataPost,
    Download,
    DownloadPost,
    Histogram,
    HistogramPost,
    SchemaCsv,
    SchemaSql,
    Stats,
    StatsPost,
    Top,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
