#!/bin/bash -eu
run() {
	echo "$*"
	"$@"
}

sim=`basename $0`

base="${1:-/mnt/ceph/users/rsomerville/lyung_drives_2021Dec/PAPER_VI/JWST_Deep/run_20220111}"
field=deep
file=lightcone_nc.dat
for real in `seq 0 7` ; do
  for part in $base/$field.$real/part_z*_z* ; do
    pz=$(basename $part)
    pz=${pz#part_z}
    pz=${pz%_z*}
    run ~/.local/bin/flathub -i $sim -c realization=$real $real-$pz=$part/$file
  done
done
