# coding: utf-8

"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from flathub.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class CatalogMeta(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    High-level metadata for a dataset catalog
    """
    _required_property_names = set((
        'name',
        'title',
        'synopsis',
        'descr',
        'order',
    ))
    name = StrSchema
    title = StrSchema
    synopsis = StrSchema
    descr = StrSchema
    order = StrSchema
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        name: name,
        title: title,
        synopsis: synopsis,
        descr: descr,
        order: order,
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'CatalogMeta':
        return super().__new__(
            cls,
            *args,
            name=name,
            title=title,
            synopsis=synopsis,
            descr=descr,
            order=order,
            _configuration=_configuration,
        )
