"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flathub
from flathub.model.field_value import FieldValue
from flathub.model.filter_range import FilterRange
from flathub.model.filter_wildcard import FilterWildcard
globals()['FieldValue'] = FieldValue
globals()['FilterRange'] = FilterRange
globals()['FilterWildcard'] = FilterWildcard
from flathub.model.filters_value import FiltersValue


class TestFiltersValue(unittest.TestCase):
    """FiltersValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFiltersValue(self):
        """Test FiltersValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FiltersValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
