"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attachments_request_all_of import AttachmentsRequestAllOf
from openapi_client.model.field_list import FieldList
from openapi_client.model.filters import Filters
globals()['AttachmentsRequestAllOf'] = AttachmentsRequestAllOf
globals()['FieldList'] = FieldList
globals()['Filters'] = Filters
from openapi_client.model.attachments_request import AttachmentsRequest


class TestAttachmentsRequest(unittest.TestCase):
    """AttachmentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentsRequest(self):
        """Test AttachmentsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
