"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.field_value_scalar import FieldValueScalar
globals()['FieldValueScalar'] = FieldValueScalar
from openapi_client.model.field_value import FieldValue


class TestFieldValue(unittest.TestCase):
    """FieldValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldValue(self):
        """Test FieldValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
