"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flathub
from flathub.model.filters import Filters
globals()['Filters'] = Filters
from flathub.model.attachments1_request import Attachments1Request


class TestAttachments1Request(unittest.TestCase):
    """Attachments1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachments1Request(self):
        """Test Attachments1Request"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Attachments1Request()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
