"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flathub
from flathub.model.download_request_all_of import DownloadRequestAllOf
from flathub.model.field_list import FieldList
from flathub.model.filters import Filters
from flathub.model.sort import Sort
globals()['DownloadRequestAllOf'] = DownloadRequestAllOf
globals()['FieldList'] = FieldList
globals()['Filters'] = Filters
globals()['Sort'] = Sort
from flathub.model.download_request import DownloadRequest


class TestDownloadRequest(unittest.TestCase):
    """DownloadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDownloadRequest(self):
        """Test DownloadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DownloadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
