"""
    FlatHUB API

    Most operations support GET and POST, either of which accepts JSON request bodies or query parameters.  In most cases, query parameters are ignored when there is a request body.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flathub
from flathub.model.histogram_list import HistogramList
globals()['HistogramList'] = HistogramList
from flathub.model.histogram_parameters import HistogramParameters


class TestHistogramParameters(unittest.TestCase):
    """HistogramParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistogramParameters(self):
        """Test HistogramParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HistogramParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
